# See http://goreleaser.com about this file
before:
  hooks:
    - go mod download
builds:
- main: ./cmd/binq/main.go
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  env:
  - CGO_ENABLED=0
archives:
- format: zip
  files:
    - nothing*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
brews:
- tap:
    owner: progrhyme
    name: homebrew-tap
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  folder: Formula
  homepage: https://binqry.github.io/
  description: A light-weight software installer written in Golang
  test: |
    system "#{bin}/binq", 'version'
